-- What the fuck is this
-- EnemyPropertyChanges = {{
--     TraitName = "GunLoadedGrenadeTrait",
--     LegalUnits = {"GunBombUnit"},
--     ThingProperty = "Graphic",
--     ChangeValue = "LuciferBomb-Artemis",
--     ChangeType = "Absolute"
-- }},
-- PropertyChanges = {{
--     WeaponName = "SwordParry",
--     ProjectileProperty = "DetonateGraphic",
--     ChangeValue = "RadialNovaSwordParry-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     WeaponName = "SpearWeaponThrow",
--     ProjectileProperty = "Graphic",
--     ChangeValue = "SpearThrowProjectile-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     WeaponName = "SpearWeaponThrowReturn",
--     ProjectileProperty = "Graphic",
--     ChangeValue = "SpearThrowProjectile-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     WeaponName = "SpearWeaponThrow",
--     ProjectileProperty = "StartFx",
--     ChangeValue = "ArtemisSpearThrowStartFx",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     WeaponName = "BowSplitShot",
--     ProjectileProperty = "Graphic",
--     ChangeValue = "BowWeaponArrow-Artemis-SplitShot",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     WeaponName = "BowSplitShot",
--     WeaponProperty = "MinChargeStartFx",
--     ChangeValue = "BowCharge-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     WeaponNames = {"ShieldThrow", "ShieldThrowDash"},
--     ProjectileName = "ShieldThrow",
--     ProjectileProperty = "DetonateGraphic",
--     ChangeValue = "ShieldSwipe-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     WeaponNames = {"ShieldThrowDash"},
--     ProjectileName = "ShieldThrowDash",
--     ProjectileProperty = "DetonateGraphic",
--     ChangeValue = "ShieldSwipe-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     WeaponNames = {"ShieldThrow", "ShieldThrowDash"},
--     WeaponProperty = "ChargeStartFx",
--     ChangeValue = "ShieldCharge-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     WeaponName = "GunGrenadeToss",
--     ProjectileProperty = "DetonateGraphic",
--     ChangeValue = "ZagGrenadeExplosionArtemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     WeaponNames = {"ShieldThrow", "ShieldThrowDash"},
--     ProjectileProperty = "Graphic",
--     ChangeValue = "ProjectileShield-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "ShieldRushBonusProjectileTrait",
--     ProjectileProperty = "Graphic",
--     WeaponNames = {"ShieldThrow", "ShieldThrowDash", "ChaosShieldThrow"},
--     ChangeValue = "ProjectileShieldAlt01-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "ShieldLoadAmmoTrait",
--     ProjectileProperty = "Graphic",
--     WeaponNames = {"ShieldThrow", "ShieldThrowDash", "ChaosShieldThrow"},
--     ChangeValue = "ProjectileShieldAlt03-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "ShieldTwoShieldTrait",
--     ProjectileProperty = "Graphic",
--     WeaponName = "ShieldThrow",
--     ChangeValue = "ProjectileShieldAlt02-Poseidon",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "ShieldTwoShieldTrait",
--     WeaponName = "ShieldThrow",
--     ProjectileName = "ShieldThrow",
--     ProjectileProperty = "DetonateGraphic",
--     ChangeValue = "ShieldThrowTrailMirage-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     WeaponName = "GunGrenadeToss",
--     WeaponProperty = "FireFx",
--     ChangeValue = "SwordSwipeAFlipped-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     WeaponName = "GunGrenadeToss",
--     ProjectileProperty = "StartFx",
--     ChangeValue = "SwordSwipeA-Emitter-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "SpearTeleportTrait",
--     WeaponName = "SpearRushWeapon",
--     ProjectileName = "SpearRushWeapon",
--     ProjectileProperty = "DetonateGraphic",
--     ChangeValue = "SpearRushTrailFx-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     WeaponNames = {"FistWeaponSpecial", "FistWeaponSpecialDash"},
--     WeaponProperty = "FireFx",
--     ChangeValue = "FistFxUppercutDirectionalArtemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "GunLoadedGrenadeTrait",
--     WeaponNames = {"GunGrenadeToss"},
--     ProjectileProperty = "Graphic",
--     ChangeValue = "GunGrenadeLuciferOrb-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "GunLoadedGrenadeTrait",
--     WeaponNames = {"GunGrenadeToss"},
--     ProjectileProperty = "GroupName",
--     ChangeValue = "FX_Standing_Add",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "GunLoadedGrenadeTrait",
--     WeaponNames = {"GunBombWeapon"},
--     ProjectileProperty = "DetonateGraphic",
--     ChangeValue = "ZagGrenadeExplosionArtemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "GunLoadedGrenadeTrait",
--     WeaponName = "GunGrenadeToss",
--     ProjectileProperty = "StartFx",
--     ChangeValue = "null",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "GunLoadedGrenadeTrait",
--     WeaponName = "GunGrenadeToss",
--     WeaponProperty = "FireFx",
--     ChangeValue = "null",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "GunLoadedGrenadeTrait",
--     WeaponNames = {"GunBombImmolation"},
--     ProjectileProperty = "DetonateGraphic",
--     ChangeValue = "LuciferOrbAoE-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "BowMarkHomingTrait",
--     WeaponNames = {"BowSplitShot"},
--     ProjectileProperty = "Graphic",
--     ChangeValue = "BowWeaponArrow-Artemis-SplitShot-Alt01",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "BowLoadAmmoTrait",
--     WeaponNames = {"BowSplitShot"},
--     ProjectileProperty = "Graphic",
--     ChangeValue = "BowWeaponArrow-Artemis-SplitShot-Alt02",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "FistDetonateTrait",
--     WeaponNames = {"FistWeaponSpecial"},
--     WeaponProperty = "FireFx",
--     ChangeValue = "ClawSwipeUppercut-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "FistDetonateTrait",
--     WeaponNames = {"FistWeaponSpecialDash"},
--     WeaponProperty = "FireFx",
--     ChangeValue = "ClawSwipeUppercutSpecial-Artemis",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }, {
--     TraitName = "FistTeleportSpecialTrait",
--     WeaponNames = {"FistWeaponSpecial", "FistWeaponSpecialDash"},
--     WeaponProperty = "FireFx",
--     ChangeValue = "FistFxUppercutDirectionalArtemis_FlashKick",
--     ChangeType = "Absolute",
--     ExcludeLinked = true
-- }}
